// let users = [
//   {
//     id: 1,
//     email: "george.bluth@reqres.in",
//     first_name: "George",
//     last_name: "Bluth",
//     avatar: "https://reqres.in/img/faces/1-image.jpg",
//   },
//   {
//     id: 2,
//     email: "janet.weaver@reqres.in",
//     first_name: "Janet",
//     last_name: "Weaver",
//     avatar: "https://reqres.in/img/faces/2-image.jpg",
//   },
//   {
//     id: 3,
//     email: "emma.wong@reqres.in",
//     first_name: "Emma",
//     last_name: "Wong",
//     avatar: "https://reqres.in/img/faces/3-image.jpg",
//   },
//   {
//     id: 4,
//     email: "eve.holt@reqres.in",
//     first_name: "Eve",
//     last_name: "Holt",
//     avatar: "https://reqres.in/img/faces/4-image.jpg",
//   },
//   {
//     id: 5,
//     email: "charles.morris@reqres.in",
//     first_name: "Charles",
//     last_name: "Morris",
//     avatar: "https://reqres.in/img/faces/5-image.jpg",
//   },
//   {
//     id: 8,
//     email: "lindsay.ferguson@reqres.in",
//     first_name: "Lindsay",
//     last_name: "Ferguson",
//     avatar: "https://reqres.in/img/faces/8-image.jpg",
//   },
//   {
//     id: 9,
//     email: "tobias.funke@reqres.in",
//     first_name: "Tobias",
//     last_name: "Funke",
//     avatar: "https://reqres.in/img/faces/9-image.jpg",
//   },
//   {
//     id: 10,
//     email: "byron.fields@reqres.in",
//     first_name: "Byron",
//     last_name: "Fields",
//     avatar: "https://reqres.in/img/faces/10-image.jpg",
//   },
//   {
//     id: 11,
//     email: "george.edwards@reqres.in",
//     first_name: "George",
//     last_name: "Edwards",
//     avatar: "https://reqres.in/img/faces/11-image.jpg",
//   },
//   {
//     id: 12,
//     email: "rachel.howell@reqres.in",
//     first_name: "Rachel",
//     last_name: "Howell",
//     avatar: "https://reqres.in/img/faces/12-image.jpg",
//   },
//   {
//     id: 6,
//     email: "tracey.ramos@reqres.in",
//     first_name: "Tracey",
//     last_name: "Ramos",
//     avatar: "https://reqres.in/img/faces/6-image.jpg",
//   },
//   {
//     id: 7,
//     email: "michael.lawson@reqres.in",
//     first_name: "Michael",
//     last_name: "Lawson",
//     avatar: "https://reqres.in/img/faces/7-image.jpg",
//   },
// ];


let users=[
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
  },
  {
    id: 2,
    title: "Bokhari Barghi",
    price: 899,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
  },
  {
    id: 6,
    title: "MacBook Pro",
    price: 1749,
    rating: 4.57,
    stock: 83,
    brand: "Apple",
    category: "laptops",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    price: 1499,
    rating: 4.25,
    stock: 50,
    brand: "Samsung",
    category: "laptops",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    price: 1499,
    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    price: 1099,
    rating: 4.54,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    price: 1099,
    rating: 4.43,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
  },
  {
    id: 11,
    title: "perfume Oil",
    price: 13,
    rating: 4.26,
    stock: 65,
    brand: "Impression of Acqua Di Gio",
    category: "fragrances",
  },
  {
    id: 12,
    title: "Brown Perfume",
    price: 40,
    rating: 4,
    stock: 52,
    brand: "Royal_Mirage",
    category: "fragrances",
  },
  {
    id: 13,
    title: "Fog Scent Xpressio Perfume",
    price: 13,
    rating: 4.59,
    stock: 61,
    brand: "Fog Scent Xpressio",
    category: "fragrances",
  },
  {
    id: 14,
    title: "Non-Alcoholic Concentrated Perfume Oil",
    price: 120,
    rating: 4.21,
    stock: 114,
    brand: "Al Munakh",
    category: "fragrances",
  },
  {
    id: 15,
    title: "Eau De Perfume Spray",
    price: 30,
    rating: 4.7,
    stock: 105,
    brand: "Lord - Al-Rehab",
    category: "fragrances",
  },
  {
    id: 16,
    title: "Hyaluronic Acid Serum",
    price: 19,
    rating: 4.83,
    stock: 110,
    brand: "L'Oreal Paris",
    category: "skincare",
  },
  {
    id: 17,
    title: "Tree Oil 30ml",
    price: 12,
    rating: 4.52,
    stock: 78,
    brand: "Hemani Tea",
    category: "skincare",
  },
  {
    id: 18,
    title: "Oil Free Moisturizer 100ml",
    price: 40,
    rating: 4.56,
    stock: 88,
    brand: "Dermive",
    category: "skincare",
  },
  {
    id: 19,
    title: "Skin Beauty Serum.",
    price: 46,
    rating: 4.42,
    stock: 54,
    brand: "ROREC White Rice",
    category: "skincare",
  },
  {
    id: 20,
    title: "Freckle Treatment Cream- 15gm",
    price: 70,
    rating: 4.06,
    stock: 140,
    brand: "Fair & Clear",
    category: "skincare",
  },
  {
    id: 21,
    title: "- Daal Masoor 500 grams",
    price: 20,
    rating: 4.44,
    stock: 133,
    brand: "Saaf & Khaas",
    category: "groceries",
  },
  {
    id: 22,
    title: "Elbow Macaroni - 400 gm",
    price: 14,
    rating: 4.57,
    stock: 146,
    brand: "Bake Parlor Big",
    category: "groceries",
  },
  {
    id: 23,
    title: "Orange Essence Food Flavou",
    price: 14,
    rating: 4.85,
    stock: 26,
    brand: "Baking Food Items",
    category: "groceries",
  },
  {
    id: 24,
    title: "cereals muesli fruit nuts",
    price: 46,
    rating: 4.94,
    stock: 113,
    brand: "fauji",
    category: "groceries",
  },
  {
    id: 25,
    title: "Gulab Powder 50 Gram",
    price: 70,
    rating: 4.87,
    stock: 47,
    brand: "Dry Rose",
    category: "groceries",
  },
  {
    id: 26,
    title: "Plant Hanger For Home",
    price: 41,
    rating: 4.08,
    stock: 131,
    brand: "Boho Decor",
    category: "home-decoration",
  },
  {
    id: 27,
    title: "Hassan",
    price: 51,
    rating: 4.41,
    stock: 17,
    brand: "Flying Wooden",
    category: "home-decoration",
  },
];
